from enum import Enum, auto

class Skill(Enum):
    LOGIC = auto()
    ENCYCLOPEDIA = auto()
    RHETORIC = auto()
    DRAMA = auto()
    CONCEPTUALIZATION = auto()
    VISUALCALCULUS = auto()
    VOLITION = auto()
    INLANDEMPIRE = auto()
    EMPATHY = auto()
    AUTHORITY = auto()
    ESPRITDECORPS = auto()
    SUGGESTION = auto()
    ENDURANCE = auto()
    PAINTHRESHOLD = auto()
    PHYSICALINSTRUMENT = auto()
    ELECTROCHEMISTRY = auto()
    SHIVERS = auto()
    HALFLIGHT = auto()
    HANDEYECOORDINATION = auto()
    PERCEPTION = auto()
    REACTIONSPEED = auto()
    SAVOIRFAIRE = auto()
    INTERFACING = auto()
    COMPOSURE = auto()
